development:
  adapter: postgresql
  encoding: unicode
  database: rsearch
  username: admin
  password: admin
  host: 192.168.0.102
  port: 5432
  pool: 500

production:
  adapter: postgresql
  encoding: unicode
  database: rsearch
  username: admin
  password: admin
  host: 192.168.0.102
  port: 5432
  pool: 500
