production:
  solr:
    hostname: localhost
    port: 8984
    log_level: WARNING
    path: /solr/rsearch
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8984
    log_level: INFO
    path: /solr/rsearch

test:
  solr:
    hostname: localhost
    port: 8984
    log_level: WARNING
    path: /solr/rsearch
    